import { ResponseMessage } from '@/types';

export const mockHops: Array<ResponseMessage> = [
  { success: false, failureReason: 'private' },
  {
    success: true,
    hopInfo: {
      ip: '41.238.104.1',
      city: 'Alexandria',
      region: 'ALX',
      organization: 'TE Data',
      country: 'Egypt',
      lat: 35.9977,
      lng: 25.7432,
      ISP: 'TE Data',
    },
  },
  { success: false, failureReason: 'private' },
  { success: false, failureReason: 'private' },
  { success: false, failureReason: 'private' },
  { success: false, failureReason: 'private' },
  {
    success: true,
    hopInfo: {
      ip: '212.222.6.234',
      city: 'Warsaw',
      region: '14',
      organization: 'GTT EU',
      country: 'Poland',
      lat: 52.2297,
      lng: 21.0122,
      ISP: 'GTT Communications Inc.',
    },
  },
  {
    success: true,
    hopInfo: {
      ip: '212.222.6.229',
      city: 'Warsaw',
      region: '14',
      organization: 'GTT EU',
      country: 'Poland',
      lat: 52.2297,
      lng: 21.0122,
      ISP: 'GTT Communications Inc.',
    },
  },
  {
    success: true,
    hopInfo: {
      ip: '213.200.116.225',
      city: 'London',
      region: 'ENG',
      organization: 'Tinet SpA',
      country: 'United Kingdom',
      lat: 51.5074,
      lng: -0.127758,
      ISP: 'GTT',
    },
  },
  {
    success: true,
    hopInfo: {
      ip: '87.119.94.70',
      city: 'London',
      region: 'ENG',
      organization: '',
      country: 'United Kingdom',
      lat: 51.5072,
      lng: -0.127586,
      ISP: 'GTT',
    },
  },
  { success: false, failureReason: 'timeout' },
  { success: false, failureReason: 'timeout' },
  {
    success: true,
    hopInfo: {
      ip: '140.82.121.3',
      city: 'Frankfurt am Main',
      region: 'HE',
      organization: 'GitHub, Inc.',
      country: 'Germany',
      lat: 50.1188,
      lng: 8.6843,
      ISP: 'GitHub, Inc.',
    },
  },
];
